/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_yqy7_nativejni_TestJni */

#ifndef _Included_com_github_yqy7_nativejni_TestJni
#define _Included_com_github_yqy7_nativejni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_yqy7_nativejni_TestJni
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_yqy7_nativejni_TestJni_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
